import type { CatalogSkill } from "../types/skill";

const OPENAI_PLUGINS = "https://github.com/openai/plugins/tree/main/plugins";

export const skillCatalog: CatalogSkill[] = [
  {
    id: "general-client-brief",
    name: "Client Brief",
    description: "Turn scattered client context into a concise working brief",
    instructions: "Collect the client goal, current priorities, decision makers, deadlines, open questions, and known constraints. Keep the brief factual and concise. Separate confirmed information from assumptions that still need verification.",
    source: "general",
  },
  {
    id: "general-meeting-preparation",
    name: "Meeting Preparation",
    description: "Prepare a focused plan for an upcoming client meeting",
    instructions: "Review the available client context and produce the meeting objective, essential background, decisions needed, questions to ask, and a short agenda. Prioritize unresolved issues that can change the outcome.",
    source: "general",
  },
  {
    id: "google-drive",
    name: "Drive File Workflows",
    description: "Find, organize, share, export, copy, and remove Drive files",
    instructions: "Use Google Drive as the entry point for connected Drive, Docs, Sheets, and Slides work. Resolve the exact file before acting. Preserve the existing structure when editing, and confirm the target before sharing or deleting content.",
    source: "plugin",
    pluginId: "google-workspace",
    sourceUrl: `${OPENAI_PLUGINS}/google-drive/skills/google-drive`,
  },
  {
    id: "google-docs",
    name: "Google Docs Authoring",
    description: "Create and edit Google Docs while preserving document structure",
    instructions: "Use the connected Google Docs tools for native document work. Treat the user's requested structure and wording as authoritative. Preserve headings, lists, tables, links, and other document relationships unless the request explicitly changes them.",
    source: "plugin",
    pluginId: "google-workspace",
    sourceUrl: `${OPENAI_PLUGINS}/google-drive/skills/google-docs`,
  },
  {
    id: "google-sheets",
    name: "Google Sheets Analysis",
    description: "Inspect and edit Sheets with precise ranges and formulas",
    instructions: "Inspect the relevant sheet, tab, and range before editing. Use exact ranges, preserve formulas and formatting outside the requested scope, and verify the resulting values or chart after the change.",
    source: "plugin",
    pluginId: "google-workspace",
    sourceUrl: `${OPENAI_PLUGINS}/google-drive/skills/google-sheets`,
  },
  {
    id: "google-calendar-meeting-prep",
    name: "Calendar Meeting Prep",
    description: "Build a concise briefing from an upcoming calendar event",
    instructions: "Find the exact event, then gather its agenda, attendees, linked materials, and relevant recent context. Produce a short preparation brief with the objective, decisions needed, open questions, and follow-ups without inventing attendee details.",
    source: "plugin",
    pluginId: "google-workspace",
    sourceUrl: `${OPENAI_PLUGINS}/google-calendar/skills/google-calendar-meeting-prep`,
  },
  {
    id: "github-address-comments",
    name: "Address Pull Request Comments",
    description: "Review PR feedback and apply approved code changes",
    instructions: "Inspect the pull request, resolve each actionable review thread against the current code, and make the smallest correct changes. Verify the affected checks and summarize which comments were addressed or remain blocked.",
    source: "plugin",
    pluginId: "github",
    sourceUrl: `${OPENAI_PLUGINS}/github/skills/gh-address-comments`,
  },
  {
    id: "github-fix-ci",
    name: "Fix CI Failures",
    description: "Trace failing GitHub checks and implement a focused fix",
    instructions: "Read the failing check output first, identify the first relevant failure, and trace it to the owning code or configuration. Implement only the required fix, rerun the narrowest useful verification, and report any failures outside the change.",
    source: "plugin",
    pluginId: "github",
    sourceUrl: `${OPENAI_PLUGINS}/github/skills/gh-fix-ci`,
  },
  {
    id: "notion-meeting-intelligence",
    name: "Meeting Intelligence",
    description: "Turn meeting notes into decisions, owners, and follow-ups",
    instructions: "Find the relevant meeting notes and extract decisions, action items, owners, deadlines, and unresolved questions. Keep links to the source material and do not infer commitments that are not present in the notes.",
    source: "plugin",
    pluginId: "notion",
    sourceUrl: `${OPENAI_PLUGINS}/notion/skills/notion-meeting-intelligence`,
  },
  {
    id: "notion-spec-to-implementation",
    name: "Spec to Implementation",
    description: "Translate a Notion specification into grounded implementation work",
    instructions: "Read the complete source specification, identify requirements and unresolved decisions, then map confirmed requirements to the current codebase. Keep implementation work traceable to the source and surface contradictions before choosing a direction.",
    source: "plugin",
    pluginId: "notion",
    sourceUrl: `${OPENAI_PLUGINS}/notion/skills/notion-spec-to-implementation`,
  },
  {
    id: "linear-issue-workflow",
    name: "Linear Issue Workflow",
    description: "Create, update, and organize Linear issues and projects",
    instructions: "Resolve the correct team and project before changing work. Keep issue titles concrete, preserve existing context, and make status, priority, assignee, and due-date changes only when supported by the request.",
    source: "plugin",
    pluginId: "linear",
    sourceUrl: `${OPENAI_PLUGINS}/linear/skills/linear`,
  },
  {
    id: "atlassian-status-report",
    name: "Generate Status Report",
    description: "Build a project update from Jira and Confluence evidence",
    instructions: "Gather the relevant Jira work and linked Confluence context for the reporting period. Summarize completed work, active work, blockers, risks, and next steps with links to supporting items. Distinguish source facts from interpretation.",
    source: "plugin",
    pluginId: "atlassian",
    sourceUrl: `${OPENAI_PLUGINS}/atlassian-rovo/skills/generate-status-report`,
  },
  {
    id: "vercel-investigation",
    name: "Deployment Investigation",
    description: "Trace a Vercel failure through deployment, logs, and configuration",
    instructions: "Inspect the affected deployment and its runtime or build logs before changing code. Check environment and project configuration relevant to the first failure, verify the smallest likely fix, and keep observed facts separate from hypotheses.",
    source: "plugin",
    pluginId: "vercel",
    sourceUrl: `${OPENAI_PLUGINS}/vercel/skills/investigation-mode`,
  },
  {
    id: "slack-reply-drafting",
    name: "Reply Drafting",
    description: "Draft a contextual Slack reply without sending it automatically",
    instructions: "Read the relevant thread and nearby conversation before drafting. Match the channel and relationship, answer the actual question, keep the reply concise, and never send it without explicit approval.",
    source: "plugin",
    pluginId: "slack",
    sourceUrl: `${OPENAI_PLUGINS}/slack/skills/slack-reply-drafting`,
  },
  {
    id: "browser-web-workflows",
    name: "Web Workflows",
    description: "Navigate sites and complete multi-step browser tasks",
    instructions: "Use Browser Use to work through the live site in the user's Chrome session. Inspect the current page with an accessibility snapshot, interact through stable element references and accessible locators, and verify the resulting page state after each meaningful transition. Use tabs deliberately when a workflow opens or needs another page.",
    source: "plugin",
    pluginId: "browser-use",
    sourceUrl: "https://playwright.dev/docs/locators",
  },
  {
    id: "browser-research-extraction",
    name: "Web Research and Extraction",
    description: "Find and extract structured information from live websites",
    instructions: "Navigate to the exact source, use browser snapshots and find operations to locate relevant content, and extract only information supported by the visible page. Preserve source URLs and distinguish page content from conclusions. Use additional tabs when comparing multiple sources.",
    source: "plugin",
    pluginId: "browser-use",
    sourceUrl: "https://playwright.dev/mcp/introduction",
  },
  {
    id: "browser-forms-and-files",
    name: "Forms and Files",
    description: "Complete forms, upload files, and handle browser downloads",
    instructions: "Inspect labels and current field values before filling a form. Use structured form tools where possible, handle dialogs explicitly, and verify submission results. For downloads, begin waiting for the download before triggering it and save the completed artifact to the configured browser artifact directory. Confirm the exact local file before uploading it.",
    source: "plugin",
    pluginId: "browser-use",
    sourceUrl: "https://playwright.dev/docs/downloads",
  },
  {
    id: "browser-debugging",
    name: "Browser Debugging",
    description: "Inspect console output, network traffic, storage, and page behavior",
    instructions: "Reproduce the browser problem first, then inspect console messages and relevant network requests. Use request details, cookies, local storage, tracing, or targeted JavaScript evaluation only as needed to explain the observed behavior. Keep observed failures separate from hypotheses and verify any change in the live page.",
    source: "plugin",
    pluginId: "browser-use",
    sourceUrl: "https://playwright.dev/mcp/introduction",
  },
  {
    id: "browser-visual-verification",
    name: "Visual Verification",
    description: "Verify browser UI with snapshots, screenshots, and recordings",
    instructions: "Use accessibility snapshots for interaction and screenshots for visual evidence. Check the requested state at the relevant viewport, capture focused evidence, and use tracing or video when a sequence cannot be established from a final screenshot alone. Report console or page errors that materially affect the verification.",
    source: "plugin",
    pluginId: "browser-use",
    sourceUrl: "https://playwright.dev/docs/getting-started-mcp",
  },
];
